import PrototypeWork from './PrototypeWork';
import ProjectFacts from './ProjectFacts';
import { caseDetails, Contribution, PreviewAnnotations, DesignConsiderations, ExploreRemake } from './CaseStudyDetails';
const base = import.meta.env.BASE_URL;
const image = name => `${base}assets/${name}`;
export const flagshipProjects = [
 {slug:'project-gamification',title:'Gamification & Learning Platform',category:'EMPLOYEE EXPERIENCE / LEARNING',image:'gamification.png',alt:'Independent learning dashboard concept with employee progress, resources, and leaderboards',problem:'Bring employee learning, events, and participation into one coherent experience.',outcome:'A centralized platform for interactive learning and employee engagement.',role:'Lead UX/UI Designer & Full-Stack Developer',focus:'User flows · Prototyping · Interface systems',decision:'Connect profiles, learning content, events, and leaderboards through a shared interface hierarchy. Make participation and progress visible within the same experience.',execution:'Created wireframes, user flows, prototypes, and high-fidelity Figma designs. Led frontend implementation and collaborated with backend and database teams on SQL integration.',prototype:'https://grain-fluid-14768550.figma.site/',source:'project-gamification',reflection:'Learning design needs to connect the next useful action with progress. The independent remake explores that relationship; engagement or learning gains have not been measured here.'},
 {slug:'project-bsa',title:'Broadcasting Services Platform',category:'ENTERPRISE WORKFLOWS / EVENT OPERATIONS',image:'broadcasting.png',alt:'Representative broadcasting platform concept with event scheduling and coordination',problem:'Coordinate corporate broadcasts across event requests, approvals, and production.',outcome:'A modernized coordination experience for employees and production administrators.',role:'UX/UI Designer & Full-Stack Developer',focus:'Workflow design · Interaction design · Role-based UX',decision:'Connect a multi-view calendar to event details, request states, and role-based visibility. Give employees and administrators a shared workflow while supporting their different tasks.',execution:'Created wireframes, user flows, interactive prototypes, high-fidelity UI systems, and calendar workflows. Contributed to frontend implementation and collaborated on event data structures, backend logic, and infrastructure requirements.',source:'project-broadcasting',reflection:'A calendar is one part of a coordination system. Requests, permissions, and approval states need to stay understandable as an event moves toward production.'},
 {slug:'project-asa',title:'ASA Network Management',category:'COMPLEX SYSTEMS / INFRASTRUCTURE',problem:'Make environment, node, IP configuration, and device comparison workflows easier to navigate.',outcome:'Improved how technical teams managed and compared infrastructure systems.',role:'Lead UX/UI Designer & Full-Stack Contributor',focus:'Information architecture · Technical workflows · Engineering partnership',decision:'Structure the experience around environments, nodes, devices, and gold source comparisons. Treat configuration and comparison as connected technical workflows rather than isolated screens.',execution:'Led UX/UI design, created wireframes, interaction flows, and interface architecture. Collaborated with backend, API, and database teams on technical implementation.',source:'project-asa',reflection:'Infrastructure interfaces require a clear relationship between what a user sees and what a system changes. Technical constraints belong in the design conversation from the beginning.'},
 {slug:'project-ise',title:'ISE Global Infrastructure Dashboard',category:'DATA VISUALIZATION / GLOBAL SYSTEMS',image:'operations-dashboard.png',alt:'Representative infrastructure dashboard with global topology, node health, clusters, and network analytics',problem:'Help technical teams understand servers, IP systems, and global infrastructure data in one place.',outcome:'Greater infrastructure visibility through scalable, data-driven visual experiences.',role:'UX/UI Designer & Full-Stack Developer',focus:'Data UX · Global visualization · Dashboard design',decision:'Bring global maps, server and IP tracking, filtering, and ICE cluster information into a centralized dashboard. Connect an overview of the network with the details needed to investigate it.',execution:'Designed and developed dashboard interfaces, workflows, and analytics-focused UI systems. Created interactive map-based visualizations and collaborated on frontend implementation and node and cluster data workflows.',prototype:'https://www.figma.com/make/Jo6o4zhUv1Y7vPxtPbuwIl/iseexampleprototype?t=HNOiXZn6KcWP4UDI-20&fullscreen=1',source:'project-ise',reflection:'Data visualization is useful when it supports a decision. Global context and detailed inspection should work together without requiring users to reconstruct the system across disconnected views.'}
];
const existingProjects = [...flagshipProjects];
const electron = {slug:'project-electron',title:'Electron AI Assistant',category:'CONVERSATIONAL UX / ENTERPRISE AI',image:'electron-figma.png',alt:'Independent Electron Figma remake showing the Nexus AI assistant',problem:'Help employees find internal knowledge and workflow support through conversational interaction.',outcome:'Contributed as a developer/designer to an early internal AI chatbot experience.'};
flagshipProjects.splice(0, flagshipProjects.length, existingProjects.find(p=>p.slug==='project-bsa'), existingProjects.find(p=>p.slug==='project-ise'), electron);
const additionalProjects = [existingProjects.find(p=>p.slug==='project-gamification'), existingProjects.find(p=>p.slug==='project-asa')];
export const caseProjects = [...flagshipProjects, ...additionalProjects];
const capabilities=[['Product design','Problem framing, information architecture, and interface systems for enterprise products.'],['UX research & workflows','Conversations, workflow observation, and pain-point mapping as inputs to the design process.'],['Prototyping & iteration','Wireframes, interactive Figma prototypes, stakeholder feedback, and testing to refine decisions.'],['Design + implementation','Engineering collaboration across frontend, APIs, databases, technical constraints, and AI experiences.']];
export function PortfolioHome(){return <>
 <section className="editorial-hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">SHAINA GONZALES / PRODUCT DESIGNER</p><h1 id="hero-title">Product designer.<br/><em>Systems-minded<br/>problem solver.</em></h1><p className="hero-lede">7+ years across product design and software, turning complex enterprise systems into clear, human experiences. Previously at General Motors.</p><div className="actions"><a className="button primary" href="#prototypes">View Work →</a><a className="button secondary" href={`${base}Shaina_Elizabeth_Gonzales_Design_Resume.pdf`}>Resume</a></div><p className="hero-credentials">Enterprise systems · Data visualization · AI <span>Design that understands what happens after Figma.</span></p></div><figure className="hero-project"><a href={`${base}project-ise.html`}><img src={image('operations-dashboard.png')} alt="Representative ISE dashboard showing global infrastructure and system health" /></a><figcaption><span>GLOBAL INFRASTRUCTURE / ISE</span><a href={`${base}project-ise.html`}>Explore the design story ↗</a></figcaption><p>Independent portfolio concept · not a GM production screen</p></figure></section>
 <section className="selected-editorial" id="prototypes" aria-labelledby="selected-title"><div className="section-heading"><div><p className="eyebrow">SELECTED WORK / 01—03</p><h2 id="selected-title">Complex problems.<br/>Considered solutions.</h2></div><p>Product design from the first flow to the details of implementation. Three flagship projects across event workflows, infrastructure, and enterprise AI.</p></div><p className="portfolio-caption">Project experience from General Motors, illustrated with independent portfolio remakes. The visuals and prototypes are recreated examples, not production screens.</p><div className="flagship-grid">{flagshipProjects.map((p,i)=><article className="flagship-card" key={p.slug}><a className={`flagship-visual visual-${i}`} href={`${base}${p.slug}.html`} aria-label={`Read ${p.title} case study`}>{p.image?<img src={image(p.image)} alt={p.alt} loading="lazy"/>:<div className="asa-editorial"><span>ENVIRONMENTS / NODES / DEVICES</span><strong>Designing the workflow<br/>behind the network.</strong><span>ASA / CASE STUDY<br/>Original interface imagery is not published.</span></div>}</a><div className="card-meta"><span>0{i+1}</span><span>{p.category}</span></div><h3><a href={`${base}${p.slug}.html`}>{p.title}</a></h3><p>{p.problem}</p><ProjectFacts project={p.slug.replace('project-','')} /><p className="card-outcome"><span>DESIGN CONTRIBUTION</span>{p.outcome}</p><a className="story-link" href={`${base}${p.slug}.html`}>Read the case study <span aria-hidden="true">↗</span></a></article>)}</div></section>
 <section className="capability-section"><div className="section-heading"><div><p className="eyebrow">HOW I WORK</p><h2>Understand the people.<br/>Understand the system.</h2></div><p>I connect design judgment with hands-on software experience—so the experience and its implementation can move forward together.</p></div><div className="capability-grid">{capabilities.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><a className="story-link" href={`${base}about.html#practice`}>More about my approach ↗</a></section>
 <section className="additional-work"><h2>Additional Work</h2>{[['Gamification & Learning','Learning, progress, and participation','project-gamification'],['ASA Network Management','Technical infrastructure workflows','project-asa'],['Nova Design System','Foundations, components, and accessible patterns','project-nova'],['TAD Platform','Connected workflows and enterprise integrations','project-tad']].map(([name,copy,slug])=><a key={slug} href={`${base}${slug}.html`}><h3>{name}</h3><p>{copy}</p><span aria-hidden="true">↗</span></a>)}</section>
 </>}
export function FlagshipCase({project:p}){const detail = caseDetails(p); return <>
 <section className="case-editorial"><p className="eyebrow">GENERAL MOTORS / ORIGINAL PROJECT EXPERIENCE</p><h2>{p.problem}</h2><div className="case-facts"><div><span>MY ROLE</span><p>{p.role}</p></div><div><span>DESIGN SCOPE</span><p>{p.focus}</p></div><div><span>CONTEXT</span><p>Enterprise product · General Motors</p></div></div><p className="portfolio-caption">Original project experience at General Motors. Visuals and prototypes are independent portfolio remakes with sample data; confidential production artifacts and quantitative results are not published.</p>{p.image&&<figure className="case-image"><img src={image(p.image)} alt={p.alt}/><figcaption>Independent portfolio preview{detail ? " · Reading the interface below" : ""}</figcaption>{detail && <PreviewAnnotations detail={detail} />}</figure>}
 <nav className="case-jump" aria-label="Case study sections"><a href="#challenge">Challenge</a><a href="#decisions">Design decisions</a><a href="#delivery">Delivery</a><a href="#reflection">Reflection</a>{detail && <a href="#explore">Explore the remake</a>}</nav>
 <div className="case-reading"><section id="challenge"><p className="eyebrow">01 / THE CHALLENGE</p><h3>{detail?.challengeTitle || "Make the system understandable."}</h3><p>{detail?.context || p.problem}</p>{detail && <><div className="case-tension"><h4>The design challenge</h4><p>{detail.tension}</p></div><Contribution detail={detail} /></>}</section><section id="decisions"><p className="eyebrow">02 / DESIGN DECISIONS</p><h3>{detail?.decisionTitle || "Organize around the work people do."}</h3><p>{p.decision}</p>{detail && <DesignConsiderations detail={detail} />}</section><section id="delivery"><p className="eyebrow">03 / PROTOTYPING & ENGINEERING</p><h3>{detail?.deliveryTitle || "Connect the design to implementation."}</h3><p>{p.execution}</p></section><section><p className="eyebrow">04 / DOCUMENTED OUTCOME</p><h3>{p.outcome}</h3><p>The original project brought these capabilities into a shared enterprise experience. The portfolio remake illustrates the design approach separately.</p></section><section id="reflection"><p className="eyebrow">05 / DESIGN REFLECTION</p><h3>What this work asks of a designer.</h3><p>{detail?.reflection || p.reflection}</p></section></div>
 <div className="case-evidence"><h3>My process across GM projects</h3><p>I spoke with employees and users, observed existing systems and workflows, and identified pain points before shaping flows and prototypes. Stakeholder feedback, iteration, and usability testing informed the work alongside engineering collaboration.</p><p>Retrospectives helped me reflect on the work and carry lessons into the next project. This describes my practice across GM projects; it does not attribute a specific research finding to this case study.</p></div>{detail && <ExploreRemake project={p} detail={detail} />}<div className="actions">{p.prototype&&!detail&&<a className="button primary" href={p.prototype}>Explore the independent prototype ↗</a>}<a className="button secondary" href={`https://www.shainagonzalesdesigns.com/${p.source}.html`}>Read the engineering case study ↗</a></div>
 </section>{p.slug==='project-bsa'&&<PrototypeWork mode="case"/>}</>}
