import { useState } from 'react';

const events = [
  { day: 6, title: 'Leadership broadcast', type: 'Broadcast', time: '10:00 AM', status: 'Approved' },
  { day: 12, title: 'Production planning', type: 'Planning', time: '1:00 PM', status: 'In review' },
  { day: 18, title: 'Employee town hall', type: 'Broadcast', time: '11:00 AM', status: 'Approved' },
  { day: 24, title: 'Studio rehearsal', type: 'Planning', time: '9:00 AM', status: 'Approved' },
];

export default function PrototypeWork({ mode = "gallery" }) {
  const [view, setView] = useState('Month');
  const [filter, setFilter] = useState('All events');
  const [selected, setSelected] = useState(events[0]);
  const visible = events.filter(event => filter === 'All events' || event.type === filter);
  return <section className="prototype-work" id={mode === "gallery" ? "prototypes" : "bsa-interaction"} aria-label={mode === "gallery" ? "Project prototypes" : "Broadcasting sample calendar"}>
    {mode === "gallery" && <>
    <p className="eyebrow">EXPLORE THE EXPERIENCE</p>
    <div className="practice-heading"><h2 id="prototype-title">See the thinking.<br />Try the work.</h2><p>Interactive experiences alongside the problem, my contribution, and the decisions behind the design.</p></div>
    <p className="remake-notice"><strong>Independent portfolio remakes.</strong> These designs and prototypes reinterpret my past project experience. They are not the actual GM applications, production screens, or official GM products.</p>
    <div className="prototype-cards">
      <article><a href={`${import.meta.env.BASE_URL}project-gamification.html`} className="prototype-preview"><img src="https://www.shainagonzalesdesigns.com/gamification-dashboard-concept.png" alt="Independent Gamification and Learning dashboard concept" loading="lazy" /></a><small>PORTFOLIO REMAKE · LEARNING EXPERIENCE</small><h3>Gamification &amp; Learning</h3><p>An engaging learning experience connecting resources, participation, and progress.</p><div className="project-links"><a href="https://grain-fluid-14768550.figma.site/">Try the Figma prototype</a><a href={`${import.meta.env.BASE_URL}project-gamification.html`}>Read the design story</a></div></article>
      <article><a href={`${import.meta.env.BASE_URL}project-bsa.html`} className="prototype-preview"><img src="https://www.shainagonzalesdesigns.com/preview-assets/broadcasting.png" alt="Representative broadcasting event platform interface concept" loading="lazy" /></a><small>WORKFLOW DESIGN · INTERACTION DESIGN</small><h3>BSA Calendar</h3><span className="remake-status">Remake in progress</span><p>Making event schedules, requests, and approval states easier to navigate.</p><div className="project-links"><a href={`${import.meta.env.BASE_URL}project-bsa.html#bsa-demo`}>Explore sample calendar demo</a><a href={`${import.meta.env.BASE_URL}project-bsa.html`}>Read the design story</a></div></article>
      <article><a href="https://www.figma.com/make/Jo6o4zhUv1Y7vPxtPbuwIl/iseexampleprototype?t=HNOiXZn6KcWP4UDI-20&fullscreen=1" className="prototype-preview"><img src={`${import.meta.env.BASE_URL}assets/operations-dashboard.png`} alt="Representative ISE infrastructure dashboard preview" loading="lazy" /></a><small>DATA UX · INFORMATION HIERARCHY</small><h3>ISE Platform</h3><p>Helping technical teams move from system health to the detail that matters.</p><div className="project-links"><a href="https://www.figma.com/make/Jo6o4zhUv1Y7vPxtPbuwIl/iseexampleprototype?t=HNOiXZn6KcWP4UDI-20&fullscreen=1">Try the prototype</a><a href={`${import.meta.env.BASE_URL}project-ise.html`}>Read the design story</a></div></article>
      <article className="prototype-electron"><a className="prototype-preview electron-preview" href={`${import.meta.env.BASE_URL}project-electron.html`}><img src={`${import.meta.env.BASE_URL}assets/electron-figma.png`} alt="Electron portfolio Figma remake showing the Nexus AI mobile assistant searching an HR handbook" loading="lazy" /><span className="electron-preview-label">Electron <small>AI ASSISTANT / PORTFOLIO REMAKE</small></span></a><small>AI UX · TRUST · PRODUCT STRATEGY</small><h3>Electron AI Assistant</h3><p>Bringing useful employee support and transparent interactions into one experience.</p><div className="project-links"><a href="https://www.figma.com/design/PECexQvNxp0jLedKtJRZZk/ai-chat-bot?node-id=3-3">Explore the Figma design</a><a href={`${import.meta.env.BASE_URL}project-electron.html`}>Read the design story</a></div></article>
    </div>
    </>}
    {mode === "case" && <div className="bsa-story" id="bsa-calendar"><p className="remake-notice"><strong>BSA remake in progress.</strong> A dedicated project prototype is being developed. The calendar below is a sample interaction demo, not the finished remake or the actual GM platform.</p><div className="section-topline"><span>PROJECT 05 / BSA CALENDAR</span><span>DESIGN + FRONTEND</span></div><div className="practice-heading"><h2>Bring the event workflow into focus.</h2><p>A broadcasting and event platform for coordinating corporate productions, with calendar views, event requests, approvals, and role-based visibility.</p></div>
      <div className="case-grid"><article><h3>The problem</h3><p>Corporate broadcasts need a shared view of schedules and coordination tasks, from event submission through production.</p></article><article><h3>My contribution</h3><p>UX/UI and frontend development, including wireframes, user flows, interactive prototypes, and multi-view calendar workflows.</p></article><article><h3>Design focus</h3><p>Keep schedules scannable, make approval states visible, and connect a calendar event to its supporting details.</p></article><article><h3>Outcome</h3><p>A modernized coordination experience for employees submitting events and administrators managing productions.</p></article></div>
      <div className="calendar-demo" id="bsa-demo"><div className="calendar-toolbar"><div><small>INTERACTIVE PORTFOLIO DEMO</small><h3>October 2026</h3></div><div className="calendar-tabs" aria-label="Calendar view">{['Month','Agenda'].map(item=><button key={item} aria-pressed={view===item} onClick={()=>setView(item)}>{item}</button>)}</div><label>Event type<select value={filter} onChange={e=>setFilter(e.target.value)}><option>All events</option><option>Broadcast</option><option>Planning</option></select></label></div>
      <div className="calendar-layout"><div>{view==='Month' ? <div className="calendar-grid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><div className="weekday" key={day}>{day}</div>)}{Array.from({length:35},(_,index)=>{const day=index-3; return <div className="calendar-day" key={index}>{day>0&&day<=31&&<><span>{day}</span>{visible.filter(event=>event.day===day).map(event=><button key={event.day} onClick={()=>setSelected(event)} aria-pressed={selected.day===event.day}>{event.title}</button>)}</>}</div>})}</div> : <div className="calendar-agenda">{visible.map(event=><button key={event.day} onClick={()=>setSelected(event)} aria-pressed={selected.day===event.day}><span>OCT {event.day}</span><strong>{event.title}</strong><span>{event.time} · {event.status}</span></button>)}</div>}</div><aside className="calendar-detail" aria-live="polite"><small>EVENT DETAILS</small><h3>{selected.title}</h3><p>October {selected.day}, 2026<br />{selected.time}</p><span className="calendar-status">{selected.status}</span><dl><dt>Event type</dt><dd>{selected.type}</dd><dt>Workflow</dt><dd>Request → Review → Production</dd></dl></aside></div></div>
      <p className="demo-note">Recreated interaction demo with sample events; representative previews are not production screenshots.</p><a className="bsa-source" href="https://www.shainagonzalesdesigns.com/project-broadcasting.html">Read the full engineering case study →</a>
    </div>}
  </section>;
}
